[project]
name = "mirrordft"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "jax>=0.6.1",
    "matplotlib>=3.10.3",
    "scipyx>=0.0.18",
    "transformers>=4.52.2",
    "wandb>=0.19.11",
]
